FROM plugins/base:linux-arm64

LABEL maintainer="haicheng bi <bihicheng@gmail.com>" \
  org.label-schema.name="iotserver" \
  org.label-schema.vendor="haicheng bi" \
  org.label-schema.schema-version="1.0"

COPY release/linux/arm64/iotserver /bin/

ENTRYPOINT ["/bin/iotserver"]
